######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 29 08:54:31 2014
######################################################################

CONFIG += ordered
TEMPLATE = subdirs

# Directories
SUBDIRS += filewatcher \
  runcommand \
  gateway.pro
