Document: wifigateway-server
Title: Debian wifigateway-server Manual
Author: <insert document author here>
Abstract: This manual describes what wifigateway-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wifigateway-server/wifigateway-server.sgml.gz

Format: postscript
Files: /usr/share/doc/wifigateway-server/wifigateway-server.ps.gz

Format: text
Files: /usr/share/doc/wifigateway-server/wifigateway-server.text.gz

Format: HTML
Index: /usr/share/doc/wifigateway-server/html/index.html
Files: /usr/share/doc/wifigateway-server/html/*.html
